# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

## Copy all projects to WORKDIR to restore all dependencies first
COPY ./src/broker-service/Broker.Api/*.csproj         /app/src/broker-service/Broker.Api/

RUN dotnet restore /app/src/broker-service/Broker.Api/*.csproj /property:Configuration=Release -nowarn:msb3202,nu1503

## Copy the rest to the WORKDIR
COPY ./src/broker-service/ /app/src/broker-service/

RUN dotnet publish /app/src/broker-service/Broker.Api/*.csproj --no-restore -c Release -o /app/out/

# Stage 2: Serve the built application with Kestrel
FROM mcr.microsoft.com/dotnet/aspnet:8.0 as final

ENV ASPNETCORE_URLS http://+:80

WORKDIR /app

COPY --from=build /app/out /app/

ENTRYPOINT ["dotnet", "Broker.Api.dll"]

# Debug
# CMD ["tail", "-f", "/dev/null"]