# Check: kubectl get services -n ingress-nginx (it has External IP)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-gateway
  namespace: default
spec:
  rules:
  - host: "139.59.219.225"
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: core-service
            port:
              number: 80