apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-gateway
  namespace: default
spec:
  rules:
  - host: core.khoitmp.duckdns.org
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: core-service
            port:
              number: 80