apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
spec:
  rules:
  - host: "devtmp.duckdns.org"
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: core-service
            port:
              number: 80