name: broker-service (CI/CD)

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    environment: Default

    outputs:
      image-tag: ${{ steps.gitversion.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Install GitVersion
      id: gitversion
      uses: codacy/git-version@2.7.1

    - name: Build Docker Image
      run: docker build -f Dockerfile-broker-service -t ${{ github.repository }}-broker-service:latest .

    - name: Tag Docker Image
      run: |
        docker tag ${{ github.repository }}-broker-service:latest ${{ github.repository }}-broker-service:${{ steps.gitversion.outputs.version }}
        echo "Image tagged as ${{ github.repository }}:${{ steps.gitversion.outputs.version }}"

    - name: Push Docker Image
      run: docker push ${{ github.repository }}-broker-service:${{ steps.gitversion.outputs.version }}

  deploy:
    runs-on: self-hosted
    
    environment: Default
  
    needs: build
  
    steps:
      - name: Configure kubectl
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install broker-service ./helm-chart/broker-service \
            --set deployment.image.tag=${{ needs.build.outputs.image-tag }}