name: ingress-rules (CD)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    environment: Default

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure kubectl
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy with Helm
      run: |
        helm upgrade --install nginx-gateway helm-chart/ingress-rules \
        --namespace ingress-nginx