name: ingress-controller (CD)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    environment: Default

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure kubectl
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy with Helm
      run: |
        kubectl create namespace ingress-nginx
        kubectl wait --for=condition=Established namespace/ingress-nginx --timeout=60s
        helm upgrade --install ingress-nginx helm-chart/ingress-controller \
        --namespace ingress-nginx