name: namespace (CD)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    environment: Default

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure kubectl
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy with Helm
      run: |
        kubectl apply -f helm-chart/namespace/templates/namespace.yaml
        
        until kubectl get namespace ingress-nginx > /dev/null 2>&1; do
          echo "Waiting for namespace ingress-nginx to be available..."
          sleep 10
        done

        kubectl label namespace ingress-nginx app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate namespace ingress-nginx meta.helm.sh/release-name=ingress-nginx --overwrite
        kubectl annotate namespace ingress-nginx meta.helm.sh/release-namespace=ingress-nginx --overwrite

        helm upgrade --install ingress-nginx helm-chart/namespace \
        --namespace ingress-nginx